Create TABLE [dbo].[Users] (
    [Id]                INT           NOT NULL,
    [Emri]              VARCHAR (50)  NOT NULL,
    [Mbiemri]           VARCHAR (50)  NOT NULL,
    [EmriIPrindit]      VARCHAR (50)  NULL,
	[IdUser]			VARCHAR (50)  NOT NULL,
	[Password]          VARCHAR (50)  NOT NULL,	
	[Roli]				VARCHAR (50)  NOT NULL,
    [NumriPersonal]     VARCHAR (20)  NULL,
    [DataELindjes]      DATETIME      NULL,
    [VendiLindjes]      VARCHAR (80)  NULL,
    [Adresa]            VARCHAR (100) NULL,
    [Tel]               VARCHAR (20)  NULL,
    [TelZyre]           VARCHAR (15)  NULL,
    [Email]             VARCHAR (30)  NULL,
    [DataERegjistrimit] DATETIME      CONSTRAINT [DF_Users_DataERegjistrimit] DEFAULT (getdate()) NOT NULL,
    [Gjinia]            NCHAR   (2)   NULL,
	[Edukimi]           VARCHAR (80)  NULL,
    [Eksperienca]       VARCHAR (90)  NULL,
    [Shtetesia]          VARCHAR (50)  NULL,
    CONSTRAINT [PK_User_Id] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CK_User_Gjinia] CHECK ([Gjinia]='M' OR [Gjinia]='F'),
    );